//==============================================
//= 4 Molecules loaded by states_of_water.html =
//==============================================
// Authors: Justin Fairbourn and Scott Ensign
// Created at Utah State University with support from the Chemistry department and the Center for Innovative Design and Instruction.


// Replace the generic Lorem ipsum text with the HTML you would like to appear in the description when a new molecule is loaded.
var h2o_single = {
	path: 'PDB/h2o.pdb',
	description: '<h4>Title 1 Here</h4><p>Paragraph 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Paragraph 2: Suspendisse eget lorem accumsan, vestibulum lorem fringilla, blandit ipsum. Curabitur volutpat, erat pulvinar bibendum placerat, sem lacus ornare ligula, id consequat ligula velit eu sem. Aliquam gravida turpis sed ex condimentum fermentum. Nunc ut volutpat lectus. Pellentesque vitae lacinia quam. Praesent fermentum euismod luctus. Sed at libero ac augue consequat porta in et felis. Fusce ultricies imperdiet elit. In vel leo pulvinar, tempus purus sit amet, lobortis velit. Donec et dolor a libero malesuada laoreet.</p>'
};

var h2o_liquid = {
	path: 'PDB/h2o-liquid.pdb',
	description: '<h4>Title 2 Here</h4><p>Paragraph 1: Nam ultricies quis urna non tincidunt. Curabitur aliquet augue vitae justo imperdiet congue sed sed justo. Quisque in dui ex. Vestibulum nec tortor sit amet augue tincidunt venenatis in in felis. Phasellus ligula lorem, porttitor quis magna sed, ullamcorper scelerisque ipsum. Aenean nec elit eget neque volutpat vestibulum sit amet vitae quam. Curabitur vestibulum et enim dapibus faucibus.</p><p>Paragraph 2: Morbi in ultrices diam. Nam condimentum dui nec nunc porttitor dictum. Etiam venenatis ultricies dignissim. Maecenas a libero nec arcu posuere dignissim. Integer egestas augue nulla, a posuere leo lacinia non. Vestibulum sit amet sodales leo. Quisque vel magna vel ligula placerat vestibulum eu facilisis dolor. Etiam non ante vitae nulla aliquam porta. Integer nisl neque, blandit at dui ac, commodo varius sapien. Proin fringilla luctus dapibus. In non sem porta, egestas sem eget, luctus libero. Integer posuere ac quam id vestibulum. Etiam sit amet eros pellentesque, imperdiet ligula a, vehicula lectus. Donec gravida dictum erat eget euismod. Fusce vitae eleifend felis.</p>'
};

var h2o_ice = {
	path: 'PDB/h2o-ice.pdb',
	description: '<h4>Title 3 Here</h4><p>Paragraph 1: Nam vitae euismod lacus. Vestibulum vitae tempus ante. Etiam tincidunt pretium condimentum. Nam non enim posuere erat ornare malesuada ac sit amet est. Vivamus eget nunc sit amet eros vehicula ullamcorper tempus vitae libero. Nulla pharetra purus metus. Ut laoreet massa nisi. Donec pretium, mi a maximus gravida, neque dui laoreet dolor, quis sollicitudin turpis neque bibendum ipsum. Phasellus pharetra, diam eu sagittis fringilla, libero massa vehicula massa, id volutpat eros risus et nunc. Etiam vel leo aliquam, posuere tellus sit amet, varius ante. Vestibulum quis varius mi.</p><p>Paragraph 2: Duis venenatis pellentesque mollis. Suspendisse mollis a neque quis convallis. Nunc egestas feugiat finibus. Praesent rutrum ligula ligula. Mauris ullamcorper gravida tortor, a vulputate diam pretium eget. Aliquam erat volutpat. Phasellus turpis metus, laoreet ac consectetur eu, sagittis id quam. In hac habitasse platea dictumst. Quisque eu turpis ex. Nam lacinia magna nec viverra hendrerit. Sed fringilla odio vitae ultrices pulvinar. Ut in feugiat velit. Praesent sit amet vulputate felis. Vivamus consectetur est id consectetur ornare.</p>'
};

var h2o_ice_hex = {
	path: 'PDB/h2o-ice-hex.pdb',
	description: '<h4>Title 4 Here</h4><p>Paragraph 1: Morbi lectus diam, aliquam at urna et, auctor vehicula ligula. Nulla finibus rhoncus est, faucibus vulputate risus. Donec mollis dui ac ultrices ornare. Phasellus dictum ante felis, non molestie tortor feugiat et. Donec elementum tempus purus, in ultrices libero efficitur at. Nullam nec placerat neque. Cras ut sagittis lacus, vitae convallis elit. Sed augue eros, aliquam a volutpat eget, aliquet eu ex. Nullam egestas, dolor nec mollis bibendum, arcu arcu aliquam tortor, in volutpat justo diam eu nulla. Aliquam porttitor eu enim et tempor. Duis venenatis ligula magna, id hendrerit leo vestibulum vitae.</p><p>Paragraph 2: Vivamus scelerisque dui dolor, nec ultricies eros ultrices non. Quisque pulvinar velit ac lacus elementum, aliquet tincidunt nisl facilisis. Nunc tortor erat, vestibulum lobortis turpis id, vulputate finibus neque. Proin lectus neque, malesuada vitae tempor non, facilisis a felis. Curabitur pretium magna non arcu blandit, id rhoncus ante iaculis. Mauris id eros ut eros tincidunt maximus. Ut aliquam non quam vitae ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque id tempor lacus. Aliquam erat volutpat. Sed blandit, justo et tempor eleifend, dui quam congue urna, sit amet ultrices sapien enim eget dui. Nullam mattis eu tellus nec facilisis. Maecenas sed volutpat est, non faucibus justo. Donec orci eros, tempus at euismod eget, venenatis eu augue.Mauris id eros ut eros tincidunt maximus. Ut aliquam non quam vitae ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque id tempor lacus. Aliquam erat volutpat. Sed blandit, justo et tempor eleifend, dui quam congue urna, sit amet ultrices sapien enim eget dui. Nullam mattis eu tellus nec facilisis. Maecenas sed volutpat est, non faucibus justo. Donec orci eros, tempus at euismod eget, venenatis eu augue.Mauris id eros ut eros tincidunt maximus. Ut aliquam non quam vitae ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque id tempor lacus. Aliquam erat volutpat. Sed blandit, justo et tempor eleifend, dui quam congue urna, sit amet ultrices sapien enim eget dui. Nullam mattis eu tellus nec facilisis. Maecenas sed volutpat est, non faucibus justo. Donec orci eros, tempus at euismod eget, venenatis eu augue.</p>'
};